#!/bin/bash
##### Run Civil Server #####

echo "Initializing Civil server"
PYV=`python -c "import sys;t='{v[0]}.{v[1]}'.format(v=list(sys.version_info[:2]));sys.stdout.write(t)";`
echo "Python Version: $PYV"
if [ $(echo " $PYV > 3" | bc) -eq 1 ]
then
  echo -e "\033[0;31mERROR: Python Verison Must be 2.X\033[0m"
fi

npm install
mongod --shutdown
mongod --fork --logpath /var/log/mongodb.log
node app.js
